# Cloudrun API and Static frontend
#
# .env: PORT=8080 (web)


version: '3.7'

services:
  # NginX Proxy to serve static front end
  web-proxy:
    image: nginx:1.21-alpine
    ports:
      - "5080:5080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dummy:/usr/share/nginx/html
    networks:
      - front

networks:
  front:
    driver: bridge
